


	

_СпрВидДеятельности = 
VALUES('ВыручкаДУ'[ВидДеятельности])

ВыручкаДУ

let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "WITH clients AS (#(lf)    SELECT #(lf)        _IDRRef AS id,#(lf)        _Description::VARCHAR(1000) AS name1,#(lf)        _Code::VARCHAR(1000) AS code,#(lf)        _Fld1532RRef AS client_type,#(lf)        _Fld1507 AS birthday#(lf)    FROM _Reference141X1#(lf)),#(lf)empl AS (#(lf)    SELECT #(lf)        _IDRRef AS id,#(lf)        _Description::VARCHAR(1000) AS name1#(lf)    FROM _Reference225#(lf)),#(lf)period_bounds AS (#(lf)    SELECT#(lf)        DATE_TRUNC('year', CURRENT_DATE) - INTERVAL '2 years' AS start_date,#(lf)        DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year' AS end_date#(lf)),#(lf)source_data AS (#(lf)    -- Основной регистр: Посещения (_AccumRg7575)#(lf)    SELECT #(lf)        _Period AS period,#(lf)        r132._Description::VARCHAR(1000) AS club,#(lf)        r163._Fld1761::VARCHAR(1000) AS service,#(lf)        r70._Description::VARCHAR(1000) AS division,#(lf)        e.name1 AS trainer,#(lf)        c.code AS client_code,#(lf)        c.name1 AS client_name,#(lf)        c.birthday AS client_birthday,#(lf)        CASE#(lf)            WHEN a._Fld7583 = '1' THEN 'Прочие'#(lf)            WHEN c.client_type = '\x8e3e8dea66a1d5454387ceb554c10615'::bytea THEN 'Сотрудник'#(lf)            ELSE 'Клиент'#(lf)        END AS client_type,#(lf)        CASE#(lf)            WHEN r59._Code IS NOT NULL THEN#(lf)                CASE #(lf)                    WHEN r59._Fld696RRef = '\xbf4b50662e88eb7b44046ebf4849976f'::bytea THEN 'Купон'#(lf)                    ELSE 'Клип-Карта'#(lf)                END#(lf)            ELSE 'Чек'#(lf)        END AS paiment_type,#(lf)        r59._Code::VARCHAR(1000) AS contract_code,#(lf)        r59._Description::VARCHAR(1000) AS contract,#(lf)        SUM(a._Fld7585) AS number,#(lf)        SUM(a._Fld7586) AS equity#(lf)    FROM _AccumRg7575 a#(lf)    CROSS JOIN period_bounds pb#(lf)    LEFT JOIN clients c ON a._Fld7576RRef = c.id#(lf)    LEFT JOIN empl e ON a._Fld7582RRef = e.id#(lf)    LEFT JOIN _Reference132 r132 ON a._Fld7577RRef = r132._IDRRef#(lf)    LEFT JOIN _Reference163 r163 ON a._Fld7579RRef = r163._IDRRef#(lf)    LEFT JOIN _Reference70 r70 ON r163._Fld1733RRef = r70._IDRRef#(lf)    LEFT JOIN _Reference59 r59 ON a._Fld7578_RRRef = r59._IDRRef#(lf)    WHERE #(lf)        a._Period >= pb.start_date AND a._Period < pb.end_date#(lf)        AND r163._Fld1795RRef IN (#(lf)            '\x9f007d77d46892dc47058346701d3bb6'::bytea, -- Услуга#(lf)            '\x8c807e46a4e01db54ab1c0ddf6eea237'::bytea  -- Товар#(lf)        )#(lf)        AND COALESCE(r70._Fld843RRef, '\x00'::bytea) NOT IN (#(lf)            '\x9e10e872e49a551b4968a66b95c28905'::bytea, -- Прочие членство#(lf)            '\xac626c95655c992a471b27ca8f8812cd'::bytea  -- Членство#(lf)        )#(lf)        AND COALESCE(r163._Description, '') <> 'посещение клуба'#(lf)        AND COALESCE(r70._Description, '') NOT IN (#(lf)            'Игровой зал','Восстановительный фитнес','Боевые искусства',#(lf)            'Детский клуб','Водные программы','Групповые программы',#(lf)            'Тренажёрный зал','Тренажерный зал'#(lf)        )#(lf)    GROUP BY#(lf)        a._Period, r132._Description, r163._Fld1761, r70._Description,#(lf)        e.name1, c.code, c.name1, c.birthday,#(lf)        CASE#(lf)            WHEN a._Fld7583 = '1' THEN 'Прочие'#(lf)            WHEN c.client_type = '\x8e3e8dea66a1d5454387ceb554c10615'::bytea THEN 'Сотрудник'#(lf)            ELSE 'Клиент'#(lf)        END,#(lf)        CASE#(lf)            WHEN r59._Code IS NOT NULL THEN#(lf)                CASE #(lf)                    WHEN r59._Fld696RRef = '\xbf4b50662e88eb7b44046ebf4849976f'::bytea THEN 'Купон'#(lf)                    ELSE 'Клип-Карта'#(lf)                END#(lf)            ELSE 'Чек'#(lf)        END,#(lf)        r59._Code, r59._Description#(lf)#(lf)    UNION ALL#(lf)#(lf)    -- Продажи (_AccumRg7646)#(lf)    SELECT #(lf)        _Period AS period,#(lf)        r132._Description::VARCHAR(1000) AS club,#(lf)        r163._Fld1761::VARCHAR(1000) AS service,#(lf)        r70._Description::VARCHAR(1000) AS division,#(lf)        e.name1 AS trainer,#(lf)        c.code AS client_code,#(lf)        c.name1 AS client_name,#(lf)        c.birthday AS client_birthday,#(lf)        CASE#(lf)            WHEN a._Fld7656 = '1' THEN 'Прочие'#(lf)            WHEN c.client_type = '\x8e3e8dea66a1d5454387ceb554c10615'::bytea THEN 'Сотрудник'#(lf)            ELSE 'Клиент'#(lf)        END AS client_type,#(lf)        'Чек' AS paiment_type,#(lf)        r59._Code::VARCHAR(1000) AS contract_code,#(lf)        r59._Description::VARCHAR(1000) AS contract,#(lf)        SUM(a._Fld7657) AS number,#(lf)        SUM(a._Fld7659) AS equity#(lf)    FROM _AccumRg7646 a#(lf)    CROSS JOIN period_bounds pb#(lf)    LEFT JOIN clients c ON a._Fld7648RRef = c.id#(lf)    LEFT JOIN empl e ON a._Fld7652RRef = e.id#(lf)    LEFT JOIN _Reference132 r132 ON a._Fld7653RRef = r132._IDRRef#(lf)    LEFT JOIN _Reference163 r163 ON a._Fld7649RRef = r163._IDRRef#(lf)    LEFT JOIN _Reference70 r70 ON r163._Fld1733RRef = r70._IDRRef#(lf)    LEFT JOIN _Reference59 r59 ON a._Fld7655RRef = r59._IDRRef#(lf)    WHERE #(lf)        a._Period >= pb.start_date AND a._Period < pb.end_date#(lf)        AND r163._Fld1795RRef NOT IN (#(lf)            '\x9f007d77d46892dc47058346701d3bb6'::bytea, -- Услуга#(lf)            '\x89de5e634e304b1a44efac5ab7088373'::bytea, -- Абонемент#(lf)            '\xbaad3eba9d9fe9b441d2a1a897435c33'::bytea  -- ПодарочныйСертификат#(lf)        )#(lf)        AND COALESCE(r70._Fld843RRef, '\x00'::bytea) NOT IN (#(lf)            '\x9e10e872e49a551b4968a66b95c28905'::bytea, -- Прочие членство#(lf)            '\xac626c95655c992a471b27ca8f8812cd'::bytea  -- Членство#(lf)        )#(lf)        AND COALESCE(r163._Description, '') <> 'посещение клуба'#(lf)        AND COALESCE(r70._Description, '') NOT IN (#(lf)            'Игровой зал','Восстановительный фитнес','Боевые искусства',#(lf)            'Детский клуб','Водные программы','Групповые программы',#(lf)            'Тренажёрный зал','Тренажерный зал'#(lf)        )#(lf)    GROUP BY#(lf)        a._Period, r132._Description, r163._Fld1761, r70._Description,#(lf)        e.name1, c.code, c.name1, c.birthday,#(lf)        CASE#(lf)            WHEN a._Fld7656 = '1' THEN 'Прочие'#(lf)            WHEN c.client_type = '\x8e3e8dea66a1d5454387ceb554c10615'::bytea THEN 'Сотрудник'#(lf)            ELSE 'Клиент'#(lf)        END,#(lf)        r59._Code, r59._Description#(lf))#(lf)-- Финальный вывод без лишних группировок (агрегация уже сделана)#(lf)SELECT#(lf)    period AS Период,#(lf)    club AS Клуб,#(lf)    service AS Услуга,#(lf)    division AS ВидДеятельности,#(lf)    trainer AS Сотрудник,#(lf)    client_code AS КодКлиента,#(lf)    client_name AS ФИО_Клиента,#(lf)    client_birthday AS ДР_Клиента,#(lf)    number AS Количество,#(lf)    equity AS Поступления,#(lf)    client_type AS ПризнакКлиента,#(lf)    paiment_type AS ТипОплаты,#(lf)    contract_code AS КодКонтракта,#(lf)    contract AS Контракт#(lf)FROM source_data#(lf)WHERE equity IS NOT NULL AND equity <> 0#(lf)ORDER BY period DESC;"),
    #"Условный столбец добавлен" = Table.AddColumn(Источник, "ТипНоменклатуры", each if Text.Contains([Услуга], "Соляная пещера") then "Соляная пещера" else if Text.Contains([Услуга], "соляной пещеры") then "Соляная пещера" else if Text.Contains([Услуга], "ущерба") then "Возмещение ущерба" else if Text.Contains([Услуга], "Солярий") then "Солярий" else if Text.Contains([Услуга], "солярий") then "Солярий" else if Text.Contains([Услуга], "Аренда замка") then "Аренда замка" else if Text.Contains([Услуга], "аренда замка") then "Аренда замка" else if [ВидДеятельности] = "Аренда полотенец и халатов" then "Аренда полотенец и халатов" else if [ВидДеятельности] = "Аренда шкафчиков" then "Аренда шкафчиков" else if [ВидДеятельности] = "Товары рецепции" then "Товары рецепции" else "Другое"),
    #"Добавлен пользовательский столбец" = Table.AddColumn(#"Условный столбец добавлен", "ФамилияИО", each let splitСотрудник = Splitter.SplitTextByDelimiter(" ", QuoteStyle.None)([Сотрудник]) in Text.Combine({splitСотрудник{0}?, " ", Text.Start(splitСотрудник{1}?, 1), Text.Middle(Text.From([Период], "ru-RU"), 2, 1), Text.Start(splitСотрудник{2}?, 1), Text.Middle(Text.From([Период], "ru-RU"), 2, 1)}), type text),
    #"Переименованные столбцы" = Table.RenameColumns(#"Добавлен пользовательский столбец",{{"ФамилияИО", "Сотрудник2"}})
in
    #"Переименованные столбцы"
