Посещения проверка ДПФУ = 
CALCULATE(
    DISTINCTCOUNT('Посещения проверка ДПФУ'[КодКлиента]),
    'Посещения проверка ДПФУ'[Период] IN VALUES('СпрДата'[Date])
)

Посещения ГП = 
CALCULATE(
    SUM('Посещения ГП'[Посетило]),  
    'Посещения ГП'[ДатаСобытия] IN VALUES('СпрДата'[Date])
)

Посещения по купону = 
CALCULATE(
    DISTINCTCOUNT('Посещения по купону'[client_code]),
    'Посещения по купону'[visit_date] IN VALUES('СпрДата'[Date])
)

Посещения проверка ДПФУ

let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "WITH clients AS (#(lf)    SELECT#(lf)        _IDRRef AS id,#(lf)        _Code::TEXT AS code,#(lf)        _Fld1532RRef AS client_type#(lf)    FROM _Reference141X1#(lf)),#(lf)main_club AS (#(lf)    SELECT#(lf)        r141._Code::TEXT AS client,#(lf)        r132._Description::TEXT AS club,#(lf)        r59._Fld671 AS startdate,#(lf)        r59._Fld672 AS enddate#(lf)    FROM _Reference59 r59#(lf)    LEFT JOIN _Reference141X1 r141 ON r59._Fld681RRef = r141._IDRRef#(lf)    LEFT JOIN _Reference132 r132 ON r59._Fld687RRef = r132._IDRRef#(lf)    WHERE#(lf)        r132._Description IS NOT NULL#(lf)        AND r59._Fld696RRef = '\xbf4b50662e88eb7b44046ebf4849976f'::bytea  -- Тип контракта = контракт#(lf)),#(lf)training_dates AS (#(lf)    SELECT #(lf)_IDRRef AS doc_ref, #(lf)_Fld3218::DATE AS training_date #(lf)FROM _Document279 WHERE _Posted = true#(lf)    UNION ALL#(lf)    SELECT #(lf)_IDRRef AS doc_ref, #(lf)_Fld4306::DATE AS training_date #(lf)FROM _Document329 WHERE _Posted = true#(lf)),#(lf)tab1 AS (#(lf)    SELECT#(lf)        td.training_date AS period,#(lf)        r132._Description::TEXT AS club,#(lf)        c.code AS client_code,#(lf)        CASE#(lf)            WHEN a._Fld7583 = '1' THEN 'Прочие'#(lf)            WHEN c.client_type = '\x8e3e8dea66a1d5454387ceb554c10615'::bytea #(lf)           THEN 'Сотрудник'#(lf)            ELSE 'Клиент'#(lf)        END AS client_type,#(lf)        CASE#(lf)            WHEN r59._Code IS NOT NULL THEN#(lf)                CASE#(lf)                    WHEN r59._Fld696RRef = '\xbf4b50662e88eb7b44046ebf4849976f'::bytea #(lf)                    THEN 'Купон'#(lf)                    ELSE 'Клип-Карта'#(lf)                END#(lf)            ELSE 'Чек'#(lf)        END AS paiment_type,#(lf)        SUM(a._Fld7585) AS number#(lf)    FROM _AccumRg7575 a#(lf)    INNER JOIN training_dates td ON a._Fld7581_RRRef = td.doc_ref#(lf)    LEFT JOIN clients c ON a._Fld7576RRef = c.id#(lf)    LEFT JOIN _Reference132 r132 ON a._Fld7577RRef = r132._IDRRef#(lf)    LEFT JOIN _Reference163 r163 ON a._Fld7579RRef = r163._IDRRef#(lf)    LEFT JOIN _Reference70 r70 ON r163._Fld1733RRef = r70._IDRRef#(lf)    LEFT JOIN _Reference59 r59 ON a._Fld7578_RRRef = r59._IDRRef#(lf)    WHERE#(lf)        td.training_date >= '2025-10-01'::DATE#(lf)        AND td.training_date < CURRENT_DATE#(lf)        AND r163._Fld1795RRef = '\x9f007d77d46892dc47058346701d3bb6'::bytea  -- Услуга#(lf)        AND COALESCE(r70._Fld843RRef, '\x00'::bytea) NOT IN (#(lf)            '\x9e10e872e49a551b4968a66b95c28905'::bytea,  -- Прочие членство#(lf)            '\xac626c95655c992a471b27ca8f8812cd'::bytea   -- Членство#(lf)        )#(lf)        AND COALESCE(r163._Description, '') <> 'посещение клуба'#(lf)        AND r70._Description::TEXT IN (#(lf)            'Игровой зал','Восстановительный фитнес','Боевые искусства',#(lf)            'Детский клуб','Водные программы','Групповые программы',#(lf)            'Тренажёрный зал','Тренажерный зал'#(lf)        )#(lf)    GROUP BY#(lf)        td.training_date,#(lf)        r132._Description,#(lf)        c.code,#(lf)        CASE#(lf)            WHEN a._Fld7583 = '1' THEN 'Прочие'#(lf)            WHEN c.client_type = '\x8e3e8dea66a1d5454387ceb554c10615'::bytea #(lf)            THEN 'Сотрудник'#(lf)            ELSE 'Клиент'#(lf)        END,#(lf)        CASE#(lf)            WHEN r59._Code IS NOT NULL THEN#(lf)                CASE#(lf)                    WHEN r59._Fld696RRef = '\xbf4b50662e88eb7b44046ebf4849976f'::bytea #(lf)                    THEN 'Купон'#(lf)                    ELSE 'Клип-Карта'#(lf)                END#(lf)            ELSE 'Чек'#(lf)        END#(lf)),#(lf)final_data AS (#(lf)    SELECT#(lf)        t.period,#(lf)        t.club,#(lf)        t.client_code,#(lf)        t.number,#(lf)        t.client_type,#(lf)        t.paiment_type,#(lf)        MAX(#(lf)            CASE#(lf)                WHEN mc.startdate IS NULL THEN NULL#(lf)                WHEN mc.startdate <= t.period AND mc.enddate >= t.period THEN mc.club#(lf)                ELSE NULL#(lf)            END#(lf)        ) AS ОсновнойКлубДоступа#(lf)    FROM tab1 t#(lf)    LEFT JOIN main_club mc ON t.client_code = mc.client#(lf)    GROUP BY#(lf)        t.period,#(lf)        t.club,#(lf)        t.client_code,#(lf)        t.number,#(lf)        t.client_type,#(lf)        t.paiment_type#(lf))#(lf)SELECT#(lf)    period AS Период,#(lf)    club AS КлубПосещения,#(lf)    client_code AS КодКлиента,#(lf)    number AS Количество,#(lf)    client_type AS ПризнакКлиента,#(lf)    paiment_type AS ТипОплаты,#(lf)    ОсновнойКлубДоступа#(lf)FROM final_data#(lf)WHERE#(lf)paiment_type <> 'Купон'#(lf)AND client_type <> 'Сотрудник'#(lf)ORDER BY period DESC;"),
    #"Строки с примененным фильтром" = Table.SelectRows(Источник, each ([ОсновнойКлубДоступа] <> "Детский развивающий центр" and [ОсновнойКлубДоступа] <> "Пушкинский" and [ОсновнойКлубДоступа] <> "Пушкинский VIP") and ([КлубПосещения] <> "Пушкинский" and [КлубПосещения] <> "Пушкинский VIP")),
    #"Сгруппированные строки" = Table.Group(#"Строки с примененным фильтром", {"Период", "КодКлиента", "КлубПосещения"}, {{"Количество", each Table.RowCount(_), Int64.Type}}),
    #"Сортированные строки" = Table.Sort(#"Сгруппированные строки",{{"Период", Order.Ascending}})
in
    #"Сортированные строки"