Абоненменты всего  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "SELECT #(lf)#(tab)cast(_Reference59._Code as varchar(1000)) КодКонтракта#(lf)#(tab),cast(_Reference141X1._Code as varchar(1000)) КодКлиента#(lf)#(tab),cast(_Reference141X1._Description as varchar(1000)) ФИО_Клиента#(lf)        , _Fld672 ДатаОкончания#(lf)        ,_Fld671 ДатаНачала#(lf)#(lf)FROM _Reference59#(lf)#(lf)left join _Reference141X1#(lf)on _Reference141X1._IDRRef=_Reference59._Fld681RRef#(lf)#(lf)left join _Reference132 #(lf)on _Reference132._IDRRef=_Reference59._Fld687RRef#(lf)#(lf)left join _Reference163 #(lf)on _Reference163._IDRRef=_Reference59._Fld685RRef#(lf)#(lf)where #(lf)_Fld672 >= '01.10.2025' #(lf)and encode(_Fld696RRef,'hex') <>'9b656ee141a764e44de79e83cd30c1b2' --Тип контракта не равно клип карта#(lf)and cast(_Reference141X1._Code as varchar(1000)) is not null#(lf)and cast(_Reference132._Description as varchar(1000)) = 'Пушкинский'#(lf)#(lf)"),
    #"Сгруппированные строки" = Table.Group(Источник, {"КодКлиента", "ДатаНачала", "ДатаОкончания"}, {{"Количество", each Table.RowCount(_), Int64.Type}})
in
    #"Сгруппированные строки"  Посещения всего  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "SELECT #(lf)    _AccumRg7575._Period::date,#(lf)    cast(_Reference141X1._Code as varchar(1000)) as КодКлиента#(lf)   ,count(encode(_AccumRg7575._Fld7578_RRRef,'hex')) as ""Количество посещений"" #(lf)    ,cast(main._Description as varchar(1000)) ОсновнойКлубДоступа#(lf)   ,cast(_Reference132._Description as varchar(1000)) КлубПосещения#(lf)FROM _AccumRg7575#(lf)#(lf)left join _Document325#(lf)    on _AccumRg7575._RecorderRRef = _Document325._IDRRef#(lf)left join _Reference141X1#(lf)    on _Document325._Fld4171RRef = _Reference141X1._IDRRef#(lf)left join _Reference59#(lf)    on   _AccumRg7575._Fld7578_RRRef = _Reference59._IDRRef#(tab)#(lf)left join _Reference163#(lf)    on _Reference59._Fld685RRef =  _Reference163._IDRRef#(lf)left join _Reference132 as main --основной клуб доступа#(lf)    on _Reference59._Fld687RRef = main._IDRRef#(tab)#(lf)left join _Reference132 --по посещению#(lf)#(tab)on _Document325._Fld4167RRef =_Reference132._IDRRef#(lf)#(lf)where #(lf)--ВидПосещенияНовый = посещение#(lf)encode(_Document325._Fld4164RRef,'hex')='9a5a4c90d2b1aede4b91dcd1abe84c43' #(lf)#(lf)and#(lf)#(lf)   date_trunc('day', _AccumRg7575._Period::date) >= '01.10.2025'#(lf)   and date_trunc('day', _AccumRg7575._Period::date) < current_date#(lf)#(lf)-- ТипКлиента = Клиент#(lf)and  encode(_Reference141X1._Fld1532RRef,'hex') = '9e8eaa7b2e77c19f4a1c22a8d9c3efa1' #(lf)#(lf)and  cast(_Reference141X1._Code as varchar(1000)) is not null#(lf)--cast(_Reference59._Code as varchar(1000)) is not null#(lf)#(lf)group by #(lf)         _AccumRg7575._Period::date,#(lf)        cast(_Reference141X1._Code as varchar(1000))#(lf)  ,cast(main._Description as varchar(1000)) #(lf)   ,cast(_Reference132._Description as varchar(1000))"),
    #"Строки с примененным фильтром" = Table.SelectRows(Источник, each ([КлубПосещения] <> "Детский развивающий центр" and [КлубПосещения] <> "Пушкинский" and [КлубПосещения] <> "Пушкинский VIP" and [КлубПосещения] <> "Управляющая компания") and ([ОсновнойКлубДоступа] <> "Пушкинский" and [ОсновнойКлубДоступа] <> "Пушкинский VIP"))
in
    #"Строки с примененным фильтром"  Посещения по купону  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "WITH constants AS (#(lf)    SELECT #(lf)        decode('4296a4bf013441d111e7cae05001072c', 'hex') AS coupons_parent_ref,#(lf)        decode('9a5a4c90d2b1aede4b91dcd1abe84c43', 'hex') AS visit_operation_ref,#(lf)        decode('bf4b50662e88eb7b44046ebf4849976f', 'hex') AS club_card_type_ref#(lf)),#(lf)#(lf)services_filtered AS (#(lf)    SELECT _IDRRef#(lf)    FROM _Reference163#(lf)    CROSS JOIN constants c#(lf)    WHERE _ParentIDRRef = c.coupons_parent_ref#(lf)),#(lf)#(lf)pz AS (#(lf)    SELECT DISTINCT#(lf)        rg._Period::date,#(lf)        encode(rg._Fld7008RRef, 'hex') AS client_link,#(lf)        cl._Code AS client_code,#(lf)        srv._Description AS service_name,#(lf)        doc._Fld4306 AS class_start,#(lf)        _Reference132._Description AS clubPZ#(lf)#(lf)    FROM _InfoRg7006 rg#(lf)    INNER JOIN _Document329 doc ON doc._IDRRef = rg._Fld7007_RRRef#(lf)    INNER JOIN _Reference141X1 cl ON cl._IDRRef = rg._Fld7008RRef#(lf)    INNER JOIN _Enum448 e ON e._IDRRef = rg._Fld7013RRef#(lf)    INNER JOIN services_filtered sf ON sf._IDRRef = rg._Fld7010RRef#(lf)    INNER JOIN _Reference163 srv ON srv._IDRRef = rg._Fld7010RRef#(lf)    INNER JOIN _Reference132 ON _Reference132._IDRRef = rg._Fld7009RRef#(lf)    WHERE #(lf)        rg._Period >= '2025-01-01'#(lf)        AND e._EnumOrder = 4#(lf)),#(lf)#(lf)visits AS (#(lf)    SELECT #(lf)        encode(_Fld4171RRef, 'hex') AS client_link,#(lf)        _Date_Time::date AS visit_date,#(lf)        _Fld4172 AS visit_start,#(lf)        clb._Description AS club#(lf)#(lf)    FROM _Document325#(lf)    CROSS JOIN constants c#(lf)#(tab)-- inner join _Reference59 on _Reference59._IDRRef =_Document325._Fld4165RRef#(lf)    INNER JOIN _Reference132 clb ON clb._IDRRef = _Document325._Fld4167RRef#(lf)    WHERE #(lf)        _Date_Time >= '2025-01-01'#(lf)        AND _Fld4164RRef = c.visit_operation_ref#(lf)        AND encode(_Fld4171RRef, 'hex') IN (SELECT client_link FROM pz) #(lf)#(tab)#(tab)-- and _Reference59._Fld696RRef = c.club_card_type_ref#(lf)),#(lf)#(lf)pz_visited AS (#(lf)    SELECT #(lf)        p.client_link,#(lf)        p.client_code,#(lf)        p.service_name,#(lf)        v.visit_date,#(lf)        v.club AS visit_club, #(lf)        p.class_start#(lf)#(tab)#(tab)-- v.contr#(lf)    FROM pz p#(lf)inner JOIN visits v #(lf)ON v.client_link = p.client_link#(lf)AND v.visit_date = p.class_start::date#(lf)and  v.visit_start <= p.class_start#(lf)and v.club   = p.clubPZ#(lf)),#(lf)#(lf)last_contract AS (#(lf)    SELECT #(lf)        encode(_Fld681RRef, 'hex') AS client_link,#(lf)#(tab)#(tab)encode(_IDRRef,'hex') as contr,#(lf)        _Fld672 AS contract_end,#(lf)        ROW_NUMBER() OVER (PARTITION BY _Fld681RRef ORDER BY _Fld672 DESC) AS rn#(lf)    FROM _Reference59 card#(lf)    CROSS JOIN constants c#(lf)    WHERE #(lf)        card._Fld696RRef = c.club_card_type_ref#(lf)        AND card._Fld672 > '2025-01-01'#(lf)        AND encode(card._Fld681RRef, 'hex') IN (SELECT client_link FROM pz_visited)#(lf))#(lf)#(lf)SELECT #(lf)    pv.visit_date::date,#(lf)    pv.client_code,#(lf)    pv.visit_club AS club,#(lf)    pv.service_name,#(lf)#(tab)lc.contr#(lf)FROM pz_visited pv#(lf)LEFT JOIN last_contract lc #(lf)    ON lc.client_link = pv.client_link AND lc.rn = 1#(lf)WHERE #(lf)pv.visit_date >= '2025-10-01' #(lf)    AND (lc.contract_end > pv.class_start OR lc.contract_end IS NULL)"),
    #"Измененный тип" = Table.TransformColumns(Источник, {{"visit_date", each DateTime.From(Date.From(_)), type datetime}}),
    #"Сгруппированные строки" = Table.Group(#"Измененный тип", {"visit_date", "client_code", "club", "service_name", "contr"}, {{"Количество", each Table.RowCount(_), Int64.Type}}),
    #"Строки с примененным фильтром" = Table.SelectRows(#"Сгруппированные строки", each ([club] <> "Детский развивающий центр" and [club] <> "Пушкинский" and [club] <> "Пушкинский VIP"))
in
    #"Строки с примененным фильтром"  Посещения ГП  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;", "#(lf)SELECT #(lf)    cast(main._Description as varchar(1000)) Клуб    #(lf)    ,_Document279._Fld3218 ДатаСобытия#(lf)    ,_InfoRg8675._Fld8677 Посетило#(lf)    ,cast(_Fld3229 as varchar(1000)) ПредставлениеДокумента    #(lf)FROM _Document279#(lf)left join _Reference132 as main on --основной клуб доступа#(lf)main._IDRRef = _Document279._Fld3224RRef#(lf)left join _Reference191 on#(lf)_Document279._Fld3227RRef= _Reference191._IDRRef#(lf)left join _InfoRg8675 on #(lf)_InfoRg8675._Fld8676RRef = _Document279._IDRRef#(lf)#(lf)where#(lf)_Fld3218 >= '01.10.2025'#(lf)and _Document279._Posted='1'#(lf)and _InfoRg8675._Fld8677 is not null#(lf)--and cast(main._Description as varchar(1000)) <> 'Пушкинский'#(lf)--and cast(main._Description as varchar(1000)) <> 'Пушкинский VIP'"),
    #"Измененный тип" = Table.TransformColumns(Источник, {{"ДатаСобытия", each DateTime.From(Date.From(_)), type datetime}}),
    #"Строки с примененным фильтром" = Table.SelectRows(#"Измененный тип", each ([Клуб] <> "Пушкинский" and [Клуб] <> "Пушкинский VIP"))
in
    #"Строки с примененным фильтром"  Состояние предЗаписи Док ПЗ  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "SELECT #(lf)#(tab)#(tab)_Period Период#(lf)#(tab)#(tab),encode(_RecorderRRef,'hex') Регистратор#(lf)#(tab)#(tab),_Active Активность#(lf)#(tab)#(tab),encode(_Fld7007_RRRef,'hex') ГрупповоеЗанятие#(lf)#(tab)#(tab),cast(_Reference141X1._Description as varchar(1000)) Контрагент#(lf),cast(_Reference141X1._Code as varchar(1000)) КодКлиента#(lf)#(tab)#(tab),cast(_Reference132._Description as varchar(1000)) Клуб#(lf)#(tab)#(tab),encode(_Fld7010RRef,'hex') Услуга#(lf)#(tab)#(tab),_Enum448._EnumOrder Состояние#(lf)--,encode(_Fld7013RRef,'hex') Состояние1#(lf)--1 - ожидание#(lf)--2-отмена#(lf)--4-прибыл#(lf)#(tab)#(tab),cast(_Reference225._Description as varchar(1000)) Сотрудник#(lf)#(tab)#(tab),encode(_Fld4358RRef,'hex') ТипВзаиморасчетов#(lf),cast(_Reference163._Description as varchar(1000)) НаименованиеУслуги#(lf)#(tab)#(tab),_Fld4306 ВремяНачала#(lf)#(tab)#(tab),_Fld4307 ВремяОкончания#(lf)#(tab)#(tab),_Date_Time Дата#(lf)#(lf)FROM _InfoRg7006#(lf)#(tab)INNER join _Reference141X1 on#(lf)#(tab)encode(_InfoRg7006._Fld7008RRef,'hex') = encode(_Reference141X1._IDRRef,'hex')#(lf)#(tab)INNER join _Reference132 on #(lf)#(tab)encode(_Reference132._IDRRef,'hex') = encode(_InfoRg7006._Fld7009RRef,'hex')#(lf)#(tab)INNER join _Document329 on #(lf)#(tab)encode(_Document329._IDRRef,'hex') = encode(_InfoRg7006._Fld7007_RRRef,'hex')#(lf)#(tab)INNER join _Reference225 on #(lf)#(tab)encode(_Reference225._IDRRef,'hex') = encode(_Document329._Fld4322RRef,'hex')#(lf)#(tab)INNER join _Enum448 on #(lf)#(tab)encode(_Enum448._IDRRef,'hex') = encode(_InfoRg7006._Fld7013RRef,'hex')#(lf)left join _Document329_VT4352 on#(lf)encode(_Document329_IDRRef,'hex') = encode(_Document329._IDRRef,'hex')#(lf)left join _Reference163 on#(lf)encode(_Reference163._IDRRef,'hex')=encode(_Fld7010RRef,'hex')#(lf)#(lf)WHERE #(lf)_Period >= '01.01.2024'#(lf)AND#(lf)(#(lf)encode(_Fld7010RRef,'hex') = 'bcd000505688c8b011ee0a8ba155d4a1' --Услуга равно спец.услуга для ИП#(lf)or encode(_Fld4358RRef,'hex') = 'a0f1524d502e0d5d4c1dfeb9d5bbb3fe'  -- ТипВзаиморасчетов равно с сотрудником#(lf))#(lf)"),
    #"Строки с примененным фильтром" = Table.SelectRows(Источник, each ([Состояние] <> 2))
in
    #"Строки с примененным фильтром"  Состояние предЗаписи Док ГП  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "--РегистрСведений.СостояниеПредварительнойЗаписи (ДОК_ГП)#(lf)SELECT #(lf)#(tab)#(tab)_Period Период#(lf)#(tab)#(tab),encode(_RecorderRRef,'hex') Регистратор#(lf)#(tab)#(tab),_Active Активность#(lf)#(tab)#(tab),encode(_Fld7007_RRRef,'hex') ГрупповоеЗанятие#(lf)#(tab)#(tab),cast(_Reference141X1._Description as varchar(1000)) Контрагент#(lf),cast(_Reference141X1._Code as varchar(1000)) КодКлиента#(lf)#(tab)#(tab),cast(_Reference132._Description as varchar(1000)) Клуб#(lf)#(tab)#(tab),encode(_Fld7010RRef,'hex') Услуга#(lf)#(tab)#(tab),_Enum448._EnumOrder Состояние#(lf)#(tab)#(tab),cast(_Reference225._Description as varchar(1000)) Сотрудник#(lf),cast(_Reference163._Description as varchar(1000)) НаименованиеУслуги#(lf)#(tab)#(tab),_Fld3218 ВремяНачала#(lf)#(tab)#(tab),_Fld3219 ВремяОкончания#(lf)#(tab)#(tab),_Date_Time Дата#(lf)#(lf)FROM _InfoRg7006#(lf)#(tab)INNER join _Reference141X1 on#(lf)#(tab)encode(_InfoRg7006._Fld7008RRef,'hex') = encode(_Reference141X1._IDRRef,'hex')#(lf)#(tab)#(tab)INNER join _Reference132 on #(lf)#(tab)#(tab)encode(_Reference132._IDRRef,'hex') = encode(_InfoRg7006._Fld7009RRef,'hex')#(lf)#(tab)#(tab)#(tab)INNER join _Document279 on #(lf)#(tab)#(tab)#(tab)encode(_Document279._IDRRef,'hex') = encode(_InfoRg7006._Fld7007_RRRef,'hex')#(lf)#(tab)#(tab)#(tab)#(tab)INNER join _Reference225 on #(lf)#(tab)#(tab)#(tab)#(tab)encode(_Reference225._IDRRef,'hex') = encode(_Document279._Fld3223RRef,'hex')#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)INNER join _Enum448 on #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)encode(_Enum448._IDRRef,'hex') = encode(_InfoRg7006._Fld7013RRef,'hex')#(lf)left join _Reference163 on#(lf)encode(_Reference163._IDRRef,'hex')=encode(_Fld7010RRef,'hex')#(lf)WHERE #(lf)_Period >= '01.01.2024'#(lf)AND#(lf)encode(_Fld7010RRef,'hex') = 'bcd000505688c8b011ee0a8ba155d4a1' --Услуга равно спец.услуга для ИП#(lf)"),
    #"Строки с примененным фильтром" = Table.SelectRows(Источник, each ([Состояние] = 1)),
    #"Добавлен пользовательский объект" = Table.AddColumn(#"Строки с примененным фильтром", "ТипВзаиморасчетов", each "Неприменимо для группового занятия"),
    #"Переупорядоченные столбцы" = Table.ReorderColumns(#"Добавлен пользовательский объект",{"Период", "Регистратор", "Активность", "ГрупповоеЗанятие", "Контрагент", "КодКлиента", "Клуб", "Услуга", "Состояние", "Сотрудник", "ТипВзаиморасчетов", "НаименованиеУслуги", "ВремяНачала", "ВремяОкончания", "Дата"})
in
    #"Переупорядоченные столбцы"  Общая РС  let
    Источник = Table.Combine({#"РС_СостояниеПредЗаписи (ДОК_ГП)", #"РС_СостояниеПредЗаписи (ДОК_ПЗ)"}),
    #"Дублированный столбец" = Table.DuplicateColumn(Источник, "ВремяНачала", "Копия ВремяНачала"),
    #"Измененный тип" = Table.TransformColumnTypes(#"Дублированный столбец",{{"Копия ВремяНачала", type date}}),
    #"Измененный тип1" = Table.TransformColumnTypes(#"Измененный тип",{{"Копия ВремяНачала", type datetime}})
in
    #"Измененный тип1"  Клубы  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "--Справочник.Клубы (Основная)#(lf)SELECT #(lf)#(tab)cast(_Description as varchar(1000)) Наименование#(lf)FROM _Reference132#(lf)"),
    #"Строки с примененным фильтром" = Table.SelectRows(Источник, each ([Наименование] <> "OnSport" and [Наименование] <> "World Class" and [Наименование] <> "_Архив" and [Наименование] <> "Детский развивающий центр" and [Наименование] <> "Коломенское" and [Наименование] <> "КЦ" and [Наименование] <> "Пушкинский" and [Наименование] <> "Пушкинский VIP" and [Наименование] <> "Управляющая компания" and [Наименование] <> "Физкульт")),
    #"Сортированные строки" = Table.Sort(#"Строки с примененным фильтром",{{"Наименование", Order.Ascending}})
in
    #"Сортированные строки"  ВИзуал 
