

Дневное планирование для Power BI (2)  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test", "#(lf)--РегистрСведений.ПланПродажПоСотрудникамДопУслуги (Основная)#(lf)SELECT #(lf)#(tab)#(tab)-- _RecorderTRef Регистратор#(lf)#(tab)#(tab)-- ,encode(_RecorderRRef,'hex') Регистратор#(lf)#(tab)#(tab)-- ,_LineNo НомерСтроки#(lf)#(tab)#(tab)-- ,_Active Активность#(lf)#(tab)#(tab)_Fld6613 as date_plan#(lf)#(tab)#(tab),cast(_Reference217._Description as varchar(1000)) as direct#(lf)#(tab)#(tab),cast(_Reference132._Description as varchar(1000)) as club#(lf)#(tab)#(tab),cast(_Reference225._Description as varchar(1000)) as empl#(lf)#(tab)#(tab),encode(_Fld6619,'hex') as client#(lf)#(tab)#(tab),cast(_Reference141X1._Description as varchar(1000)) as client_name#(lf)#(tab)#(tab),cast(_Reference141X1._Code as varchar(1000)) Код#(lf)#(tab)#(tab),cast(_Reference183._Description as varchar(1000)) as period_plan#(lf)#(tab)#(tab)-- ,_Fld6619 Уник#(lf)#(tab)#(tab),_Fld6620 as summa#(lf)#(tab)#(tab)-- ,_Fld6621 as count_count#(lf)FROM _InfoRg6612#(lf)#(lf)LEFT JOIN _Reference225#(lf)on _InfoRg6612._Fld6616RRef = _Reference225._IDRRef#(lf)    LEFT JOIN _Reference132#(lf)    on _InfoRg6612._Fld6615RRef = _Reference132._IDRRef#(lf)#(tab)#(tab)LEFT JOIN _Reference183#(lf)#(tab)#(tab)on _InfoRg6612._Fld6618RRef = _Reference183._IDRRef#(lf)#(tab)#(tab)#(tab)LEFT JOIN _Reference217#(lf)#(tab)#(tab)#(tab)on _InfoRg6612._Fld6614RRef = _Reference217._IDRRef#(lf)#(tab)#(tab)#(tab)#(tab)LEFT JOIN _Reference141X1#(lf)#(tab)#(tab)#(tab)#(tab)on _InfoRg6612._Fld6617RRef = _Reference141X1._IDRRef"),
    #"Переименованные столбцы" = Table.RenameColumns(Источник,{{"date_plan", "Дата тренировки"}, {"direct", "Подразделение"}, {"club", "Клуб"}, {"empl", "ФИО Тренера"}, {"client", "Клиент"}, {"client_name", "ИмяКлиента"}, {"period_plan", "Source.Name"}, {"summa", "Стоимость тренировки"}}),
    #"Измененный тип" = Table.TransformColumnTypes(#"Переименованные столбцы",{{"Source.Name", type date}}),
    #"Удаленные столбцы" = Table.RemoveColumns(#"Измененный тип",{"ИмяКлиента"}),
    #"Замененное значение" = Table.ReplaceValue(#"Удаленные столбцы","Тренажёрный зал","Тренажёрный зал (Штат)",Replacer.ReplaceText,{"Подразделение"}),
    #"Измененный тип1" = Table.TransformColumnTypes(#"Замененное значение",{{"Дата тренировки", type date}}),
    #"Замененное значение1" = Table.ReplaceValue(#"Измененный тип1","тренажёрный зал","Тренажёрный зал (Штат)",Replacer.ReplaceText,{"Подразделение"}),
    #"Строки с примененным фильтром" = Table.SelectRows(#"Замененное значение1", each ([Подразделение] <> "Подразделение"))
in
    #"Строки с примененным фильтром"  ДатаОбновления   let
    Source = #table(
        type table [LastRefreshTime = datetimezone],
        {{DateTimeZone.SwitchZone(DateTimeZone.UtcNow(), 3, 0)}}
    ),
    #"Измененный тип" = Table.TransformColumnTypes(Source,{{"LastRefreshTime", type date}})
in
    #"Измененный тип"  Записи админов
let
    Источник = Table.Combine({#"ПЗ Админы",#"Записи ГЗ Админы (2)"})
in
    Источник
Записи ГЗ Админы (2)
let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru;Database=gymdb_test", "#(lf)WITH staff_base AS (#(lf)    SELECT#(lf)        encode(ir._Fld6292RRef,'hex') AS Сотрудник,#(lf)        ref101._Description AS Должность,#(lf)        ir._Fld6298 AS ДатаПриема,#(lf)        CASE#(lf)            WHEN ir._Fld6299 = TIMESTAMP '0001-01-01 00:00:00'#(lf)                THEN TIMESTAMP '2099-12-31 00:00:00'#(lf)            ELSE ir._Fld6299#(lf)        END AS ДатаУвольнения#(lf)    FROM _InfoRg6291 ir#(lf)    INNER JOIN _Reference101 ref101#(lf)        ON ref101._IDRRef = ir._Fld6296RRef#(lf)    WHERE#(lf)        CASE#(lf)            WHEN ir._Fld6299 = TIMESTAMP '0001-01-01 00:00:00'#(lf)                THEN TIMESTAMP '2099-12-31 00:00:00'#(lf)            ELSE ir._Fld6299#(lf)        END > CURRENT_TIMESTAMP#(lf)        AND ref101._Description IN ('Администратор(Кассир)', 'Старший администратор')#(lf)),#(lf)#(lf)staff_filtered AS (#(lf)    SELECT#(lf)        t.Сотрудник,#(lf)        t.Должность#(lf)    FROM (#(lf)        SELECT#(lf)            sb.*,#(lf)            ROW_NUMBER() OVER (#(lf)                PARTITION BY sb.Сотрудник#(lf)                ORDER BY sb.ДатаПриема DESC#(lf)            ) AS rn#(lf)        FROM staff_base sb#(lf)    ) t#(lf)    WHERE t.rn = 1#(lf)),#(lf)#(lf)gz_admins AS (#(lf)    SELECT#(lf)        encode(d279._IDRRef,'hex') AS Ссылка,#(lf)        d279._Fld3218 AS ДатаНачала,#(lf)        d279._Fld3219 AS ДатаОкончания,#(lf)        r132._Description AS Клуб,#(lf)        r163._Description AS Номенклатура,#(lf)#(lf)cast(v._Description as varchar(1000)) as ВозрастнаяКатегория,#(lf)ft._Description as ФорматТренировки,#(lf)#(lf)        r225._Description AS ФИО_Тренера#(lf)    FROM _Document279 d279#(lf)    LEFT JOIN _Reference132 r132#(lf)        ON r132._IDRRef = d279._Fld3224RRef#(lf)    LEFT JOIN _Reference163 r163#(lf)        ON r163._IDRRef = d279._Fld3226RRef#(lf)#(lf)LEFT JOIN _Reference87 v ON v._IDRRef = r163._Fld1741RRef#(lf)LEFT JOIN _Reference248 ft ON ft._IDRRef = r163._Fld1803RRef#(lf)#(lf)    LEFT JOIN _Reference225 r225#(lf)        ON r225._IDRRef = d279._Fld3223RRef#(lf)    WHERE#(lf)        d279._Fld3218 > '2025-11-30'#(lf)        AND d279._Fld3228 = true#(lf)),#(lf)#(lf)cancelled AS (#(lf)    SELECT DISTINCT#(lf)        encode(d312._Fld3795RRef,'hex') AS ГрупповоеЗанятие,#(lf)        encode(d312._Fld3800RRef,'hex') AS Контрагент#(lf)    FROM _Document312 d312#(lf)    WHERE#(lf)        d312._Date_Time > '2025-11-30'#(lf)        AND d312._Posted = true#(lf))#(lf)#(lf)SELECT#(lf)      d283._Date_Time AS ДатаЗаписи#(lf)    , r225._Description AS ФИО_Автора#(lf)    , sf.Должность#(lf)    , r141._Code AS Код_Клиента#(lf)    , r141._Description AS ФИО_Клиента#(lf)    , gz.ДатаНачала#(lf)    , gz.ДатаОкончания#(lf)    , gz.Клуб#(lf)    , gz.Номенклатура#(lf)#(lf)    , gz.ВозрастнаяКатегория              #(lf),gz.ФорматТренировки#(lf)#(lf)    , gz.ФИО_Тренера#(lf)    , d283._Fld3297 AS equity#(lf)FROM _Document283 d283#(lf)INNER JOIN staff_filtered sf#(lf)    ON sf.Сотрудник = encode(d283._Fld644RRef,'hex')#(lf)INNER JOIN gz_admins gz#(lf)    ON gz.Ссылка = encode(d283._Fld3291RRef,'hex')#(lf)LEFT JOIN cancelled c#(lf)    ON c.ГрупповоеЗанятие = encode(d283._Fld3291RRef,'hex')#(lf)   AND c.Контрагент = encode(d283._Fld3296RRef,'hex')#(lf)LEFT JOIN _Reference225 r225#(lf)    ON r225._IDRRef = d283._Fld644RRef#(lf)LEFT JOIN _Reference141X1 r141#(lf)    ON r141._IDRRef = d283._Fld3296RRef#(lf)WHERE#(lf)    d283._Date_Time > '2025-11-30'#(lf)    AND d283._Posted = true#(lf)    AND c.ГрупповоеЗанятие IS NULL#(lf)        "),
    #"Строки с примененным фильтром1" = Table.SelectRows(Источник, each [equity] > 0),
    #"Строки с примененным фильтром" = Table.SelectRows(#"Строки с примененным фильтром1", each ([ФорматТренировки] <> "Персональная тренировка")),
    #"Замененное значение" = Table.ReplaceValue(#"Строки с примененным фильтром","Платный урок","Групповое занятие",Replacer.ReplaceText,{"ФорматТренировки"})
in
    #"Замененное значение"

ПЗ Админы  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru;Database=gymdb_test", "#(lf)WITH staff_base AS (#(lf)    SELECT#(lf)        encode(ir._Fld6292RRef,'hex') AS Сотрудник,#(lf)        ref132._Description AS Клуб,#(lf)        ref101._Description AS Должность,#(lf)        ir._Fld6298 AS ДатаПриема,#(lf)        CASE#(lf)            WHEN ir._Fld6299 = TIMESTAMP '0001-01-01 00:00:00'#(lf)                THEN TIMESTAMP '2099-12-31 00:00:00'#(lf)            ELSE ir._Fld6299#(lf)        END AS ДатаУвольнения#(lf)    FROM _InfoRg6291 ir#(lf)    LEFT JOIN _Reference132 ref132#(lf)        ON ref132._IDRRef = ir._Fld6293RRef#(lf)    LEFT JOIN _Reference101 ref101#(lf)        ON ref101._IDRRef = ir._Fld6296RRef#(lf)    WHERE#(lf)        CASE#(lf)            WHEN ir._Fld6299 = TIMESTAMP '0001-01-01 00:00:00'#(lf)                THEN TIMESTAMP '2099-12-31 00:00:00'#(lf)            ELSE ir._Fld6299#(lf)        END > CURRENT_TIMESTAMP#(lf)        AND ref101._Description IN ('Администратор(Кассир)', 'Старший администратор')#(lf)),#(lf)#(lf)staff_filtered AS (#(lf)    SELECT#(lf)        x.Сотрудник,#(lf)        x.Клуб,#(lf)        x.Должность,#(lf)        x.ДатаПриема,#(lf)        x.ДатаУвольнения#(lf)    FROM (#(lf)        SELECT#(lf)            sb.*,#(lf)            ROW_NUMBER() OVER (#(lf)                PARTITION BY sb.Сотрудник#(lf)                ORDER BY sb.ДатаПриема DESC#(lf)            ) AS rn#(lf)        FROM staff_base sb#(lf)    ) x#(lf)    WHERE x.rn = 1#(lf)),#(lf)#(lf)cancelled AS (#(lf)    SELECT DISTINCT#(lf)        encode(d313._Fld3810_RRRef,'hex') AS ПредварительнаяЗапись#(lf)    FROM _Document313 d313#(lf)    WHERE d313._Date_Time > '2025-11-30'#(lf)      AND d313._Posted = true#(lf)),#(lf)#(lf)confirmations AS (#(lf)    SELECT#(lf)        encode(a._Fld7581_RRRef,'hex') AS ГрупповоеЗанятие,#(lf)        SUM(a._Fld7586) AS equity#(lf)    FROM _AccumRg7575 a#(lf)    LEFT JOIN _Reference163 r163#(lf)        ON a._Fld7579RRef = r163._IDRRef#(lf)    LEFT JOIN _Reference70 r70#(lf)        ON r163._Fld1733RRef = r70._IDRRef#(lf)    WHERE#(lf)        r163._Fld1795RRef = '\x9f007d77d46892dc47058346701d3bb6'::bytea#(lf)        AND r70._Fld843RRef <> '\x9e10e872e49a551b4968a66b95c28905'::bytea#(lf)        AND r70._Fld843RRef <> '\xac626c95655c992a471b27ca8f8812cd'::bytea#(lf)        AND CAST(r163._Description AS VARCHAR(1000)) <> 'посещение клуба'#(lf)        AND a._Period > '2025-11-30'#(lf)    GROUP BY#(lf)        encode(a._Fld7581_RRRef,'hex')#(lf))#(lf)#(lf)SELECT#(lf)#(lf)     d329._Date_Time AS ДатаЗаписи#(lf)    , d329._Fld4306 AS ДатаНачала#(lf)    , d329._Fld4307 AS ДатаОкончания#(lf)    , r132._Description AS Клуб#(lf)    , r163._Description AS Номенклатура#(lf)#(lf),cast(v._Description as varchar(1000)) as ВозрастнаяКатегория#(lf),ft._Description as ФорматТренировки#(lf)#(lf)    , r141._code AS Код_Клиента#(lf)    , r141._Description AS ФИО_Клиента#(lf)    , r225_2._Description AS ФИО_Тренера#(lf)    , r225._Description AS ФИО_Автора#(lf)    , sf.Должность#(lf)    , cf.equity#(lf)FROM _Document329 d329#(lf)#(lf)LEFT JOIN _Reference225 r225#(lf)    ON r225._IDRRef = d329._Fld644RRef#(lf)INNER JOIN staff_filtered sf#(lf)    ON sf.Сотрудник = encode(d329._Fld644RRef,'hex')#(lf)LEFT JOIN confirmations cf#(lf)    ON cf.ГрупповоеЗанятие = encode(d329._IDRRef,'hex')#(lf)LEFT JOIN cancelled c#(lf)    ON c.ПредварительнаяЗапись = encode(d329._IDRRef,'hex')#(lf)LEFT JOIN _Reference225 r225_2#(lf)    ON r225_2._IDRRef = d329._Fld4322RRef#(lf)LEFT JOIN _Reference141X1 r141#(lf)    ON r141._IDRRef = d329._Fld4315RRef#(lf)LEFT JOIN _Reference163 r163#(lf)    ON r163._IDRRef = d329._Fld4316RRef#(lf)#(lf)LEFT JOIN _Reference87 v#(lf)    ON v._IDRRef = r163._Fld1741RRef#(lf)LEFT JOIN _Reference248 ft#(lf)    ON ft._IDRRef = r163._Fld1803RRef#(lf)#(lf)LEFT JOIN _Reference132 r132#(lf)    ON r132._IDRRef = d329._Fld4310RRef#(lf)#(lf)WHERE#(lf)    d329._Date_Time > '2025-11-30'#(lf)    AND d329._Fld4306<current_date#(lf)    AND d329._Posted = true#(lf)    AND c.ПредварительнаяЗапись IS NULL#(lf)    AND d329._Fld4311>0#(lf)ORDER BY#(lf)    cf.equity DESC#(lf)        "),
    #"Строки с примененным фильтром2" = Table.SelectRows(Источник, each [equity] > 0),
    #"Переупорядоченные столбцы" = Table.ReorderColumns(#"Строки с примененным фильтром2",{"ДатаЗаписи", "Клуб", "Номенклатура", "ДатаНачала", "ДатаОкончания", "ФИО_Тренера", "Код_Клиента", "ФИО_Клиента", "ФИО_Автора", "Должность", "equity"}),
    #"Строки с примененным фильтром" = Table.SelectRows(#"Переупорядоченные столбцы", each ([ФорматТренировки] = "Групповое занятие" or [ФорматТренировки] = "Платный урок")),
    #"Замененное значение" = Table.ReplaceValue(#"Строки с примененным фильтром","Платный урок","Групповое занятие",Replacer.ReplaceText,{"ФорматТренировки"})
in
    #"Замененное значение"  __СрЦенаЗаписи = 
DIVIDE(
    SUM('Записи админов'[equity]),
    COUNT('Записи админов'[Код_Клиента])
)


