-- SV-077. Read-only source validation for «Подготовка к продлению».
-- Execute each statement in BEGIN TRANSACTION READ ONLY.
SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname=ANY(ARRAY['_reference59','_reference141x1','_reference132','_reference163','_accumrg7575','_accumrg7478','_inforg5859','_inforg6015']) ORDER BY 1;
SELECT count(*) rows,count(DISTINCT _idrref) technical_ids,count(*) FILTER (WHERE _fld672::date-_fld671::date<30) short_duration,count(*) FILTER (WHERE _marked) marked FROM public._reference59 WHERE _fld672>=DATE '2022-01-01';
SELECT count(*) rows,count(DISTINCT (_recordertref,_recorderrref,_lineno)) technical_keys,count(*) FILTER (WHERE r._idrref IS NULL) contract_orphans,count(*) FILTER (WHERE r._idrref IS NOT NULL AND a._fld7576rref<>r._fld681rref) client_owner_mismatch,count(*) FILTER (WHERE n._idrref IS NULL) service_orphans FROM public._accumrg7575 a LEFT JOIN public._reference59 r ON r._idrref=a._fld7578_rrref LEFT JOIN public._reference163 n ON n._idrref=a._fld7579rref WHERE a._period>=DATE '2026-01-01' AND a._period<DATE '2027-01-01';
WITH i AS MATERIALIZED (SELECT _fld5860rref contract_id,_fld5862::date s,_fld5863::date e FROM public._inforg5859) SELECT count(*) rows,count(*) FILTER (WHERE e<s) reverse_intervals,count(*) FILTER (WHERE r._idrref IS NULL) contract_orphans,(SELECT count(*) FROM (SELECT contract_id,s,e,count(*) n FROM i GROUP BY 1,2,3 HAVING count(*)>1)q) exact_duplicate_groups FROM i LEFT JOIN public._reference59 r ON r._idrref=i.contract_id;
SELECT count(*) rows,count(DISTINCT (_recordertref,_recorderrref,_lineno)) technical_keys,count(*) FILTER (WHERE NOT a._active) inactive_rows,count(*) FILTER (WHERE r._idrref IS NULL) contract_orphans FROM public._accumrg7478 a LEFT JOIN public._reference59 r ON r._idrref=a._fld7479rref;
WITH i AS MATERIALIZED (SELECT _fld5860rref contract_id,_fld5862::date s,_fld5863::date e FROM public._inforg5859 WHERE _fld5862>=DATE '2026-01-01' AND _fld5862<DATE '2027-01-01'),o AS (SELECT *,max(e) OVER(PARTITION BY contract_id ORDER BY s,e ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) prior_max_e FROM i) SELECT count(*) interval_rows,count(*) FILTER(WHERE prior_max_e>s) overlap_rows,count(DISTINCT contract_id) FILTER(WHERE prior_max_e>s) overlap_contracts FROM o;
SELECT count(*) contracts,(SELECT count(*) FROM (SELECT _code FROM public._reference59 WHERE _code IS NOT NULL AND _code<>'' GROUP BY 1 HAVING count(*)>1)q) duplicate_code_groups,count(*) FILTER(WHERE club._idrref IS NULL) club_orphans FROM public._reference59 r LEFT JOIN public._reference132 club ON club._idrref=r._fld687rref;
SELECT count(*) rows,count(DISTINCT _fld6018::date) distinct_dates,count(*)-count(DISTINCT _fld6018::date) duplicate_dates,count(*) FILTER(WHERE _fld6018 IS NULL) null_dates,min(_fld6018::date) min_date,max(_fld6018::date) max_date FROM public._inforg6015;
