  Абонементы всего  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "SELECT #(lf)#(tab)cast(_Reference59._Code as varchar(1000)) КодКонтракта#(lf)#(tab),cast(_Reference141X1._Code as varchar(1000)) КодКлиента#(lf)#(tab),cast(_Reference141X1._Description as varchar(1000)) ФИО_Клиента#(lf)        , _Fld672 ДатаОкончания#(lf)        ,_Fld671 ДатаНачала#(lf)#(lf)FROM _Reference59#(lf)#(lf)left join _Reference141X1#(lf)on _Reference141X1._IDRRef=_Reference59._Fld681RRef#(lf)#(lf)left join _Reference132 #(lf)on _Reference132._IDRRef=_Reference59._Fld687RRef#(lf)#(lf)left join _Reference163 #(lf)on _Reference163._IDRRef=_Reference59._Fld685RRef#(lf)#(lf)where #(lf)_Fld672 >= '01.10.2025' #(lf)and encode(_Fld696RRef,'hex') <>'9b656ee141a764e44de79e83cd30c1b2' --Тип контракта не равно клип карта#(lf)and cast(_Reference141X1._Code as varchar(1000)) is not null#(lf)and cast(_Reference132._Description as varchar(1000)) = 'Пушкинский'#(lf)#(lf)"),
    #"Сгруппированные строки" = Table.Group(Источник, {"КодКлиента", "ДатаНачала", "ДатаОкончания"}, {{"Количество", each Table.RowCount(_), Int64.Type}})
in
    #"Сгруппированные строки"  Посещения всего  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "SELECT #(lf)    _AccumRg7575._Period::date,#(lf)    cast(_Reference141X1._Code as varchar(1000)) as КодКлиента#(lf)   ,count(encode(_AccumRg7575._Fld7578_RRRef,'hex')) as ""Количество посещений"" #(lf)FROM _AccumRg7575#(lf)#(lf)left join _Document325#(lf)    on _AccumRg7575._RecorderRRef = _Document325._IDRRef#(lf)left join _Reference141X1#(lf)    on _Document325._Fld4171RRef = _Reference141X1._IDRRef#(lf)left join _Reference59#(lf)    on   _AccumRg7575._Fld7578_RRRef = _Reference59._IDRRef#(tab)#(lf)left join _Reference163#(lf)    on _Reference59._Fld685RRef =  _Reference163._IDRRef#(lf)left join _Reference132 as main --основной клуб доступа#(lf)    on _Reference59._Fld687RRef = main._IDRRef#(tab)#(lf)left join _Reference132 --по посещению#(lf)#(tab)on _Document325._Fld4167RRef =_Reference132._IDRRef#(lf)#(lf)where #(lf)--ВидПосещенияНовый = посещение#(lf)encode(_Document325._Fld4164RRef,'hex')='9a5a4c90d2b1aede4b91dcd1abe84c43' #(lf)and #(lf)#(lf)--документ основание - абонемент#(lf)encode(_Reference163._Fld1795RRef,'hex') = '89de5e634e304b1a44efac5ab7088373' #(lf)and#(lf) #(lf)cast(main._Description as varchar(1000)) = 'Пушкинский'#(lf)and cast(_Reference132._Description as varchar(1000)) = 'Пушкинский'#(lf)#(lf)and#(lf)#(lf)   date_trunc('day', _AccumRg7575._Period::date) >= '01.10.2025'#(lf)   and date_trunc('day', _AccumRg7575._Period::date) < current_date#(lf)#(lf)-- ТипКлиента = Клиент#(lf)and  encode(_Reference141X1._Fld1532RRef,'hex') = '9e8eaa7b2e77c19f4a1c22a8d9c3efa1' #(lf)#(lf)and  cast(_Reference141X1._Code as varchar(1000)) is not null#(lf)--cast(_Reference59._Code as varchar(1000)) is not null#(lf)#(lf)group by #(lf)         _AccumRg7575._Period::date,#(lf)        cast(_Reference141X1._Code as varchar(1000))")
in
    Источник  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "WITH constants AS (#(lf)    SELECT #(lf)        decode('4296a4bf013441d111e7cae05001072c', 'hex') AS coupons_parent_ref,#(lf)        decode('9a5a4c90d2b1aede4b91dcd1abe84c43', 'hex') AS visit_operation_ref,#(lf)        decode('bf4b50662e88eb7b44046ebf4849976f', 'hex') AS club_card_type_ref#(lf)),#(lf)#(lf)services_filtered AS (#(lf)    SELECT _IDRRef#(lf)    FROM _Reference163#(lf)    CROSS JOIN constants c#(lf)    WHERE _ParentIDRRef = c.coupons_parent_ref#(lf)),#(lf)#(lf)pz AS (#(lf)    SELECT DISTINCT#(lf)        rg._Period::date,#(lf)        encode(rg._Fld7008RRef, 'hex') AS client_link,#(lf)        cl._Code AS client_code,#(lf)        srv._Description AS service_name,#(lf)        doc._Fld4306 AS class_start,#(lf)        _Reference132._Description AS clubPZ#(lf)#(lf)    FROM _InfoRg7006 rg#(lf)    INNER JOIN _Document329 doc ON doc._IDRRef = rg._Fld7007_RRRef#(lf)    INNER JOIN _Reference141X1 cl ON cl._IDRRef = rg._Fld7008RRef#(lf)    INNER JOIN _Enum448 e ON e._IDRRef = rg._Fld7013RRef#(lf)    INNER JOIN services_filtered sf ON sf._IDRRef = rg._Fld7010RRef#(lf)    INNER JOIN _Reference163 srv ON srv._IDRRef = rg._Fld7010RRef#(lf)    INNER JOIN _Reference132 ON _Reference132._IDRRef = rg._Fld7009RRef#(lf)    WHERE #(lf)        rg._Period >= '2025-01-01'#(lf)        AND e._EnumOrder = 4#(lf)),#(lf)#(lf)visits AS (#(lf)    SELECT #(lf)        encode(_Fld4171RRef, 'hex') AS client_link,#(lf)        _Date_Time::date AS visit_date,#(lf)        _Fld4172 AS visit_start,#(lf)        clb._Description AS club#(lf)#(lf)    FROM _Document325#(lf)    CROSS JOIN constants c#(lf)#(tab)-- inner join _Reference59 on _Reference59._IDRRef =_Document325._Fld4165RRef#(lf)    INNER JOIN _Reference132 clb ON clb._IDRRef = _Document325._Fld4167RRef#(lf)    WHERE #(lf)        _Date_Time >= '2025-01-01'#(lf)        AND _Fld4164RRef = c.visit_operation_ref#(lf)        AND encode(_Fld4171RRef, 'hex') IN (SELECT client_link FROM pz) #(lf)#(tab)#(tab)-- and _Reference59._Fld696RRef = c.club_card_type_ref#(lf)),#(lf)#(lf)pz_visited AS (#(lf)    SELECT #(lf)        p.client_link,#(lf)        p.client_code,#(lf)        p.service_name,#(lf)        v.visit_date,#(lf)        v.club AS visit_club, #(lf)        p.class_start#(lf)#(tab)#(tab)-- v.contr#(lf)    FROM pz p#(lf)inner JOIN visits v #(lf)ON v.client_link = p.client_link#(lf)AND v.visit_date = p.class_start::date#(lf)and  v.visit_start <= p.class_start#(lf)and v.club   = p.clubPZ#(lf)),#(lf)#(lf)last_contract AS (#(lf)    SELECT #(lf)        encode(_Fld681RRef, 'hex') AS client_link,#(lf)#(tab)#(tab)encode(_IDRRef,'hex') as contr,#(lf)        _Fld672 AS contract_end,#(lf)        ROW_NUMBER() OVER (PARTITION BY _Fld681RRef ORDER BY _Fld672 DESC) AS rn#(lf)    FROM _Reference59 card#(lf)    CROSS JOIN constants c#(lf)    WHERE #(lf)        card._Fld696RRef = c.club_card_type_ref#(lf)        AND card._Fld672 > '2025-01-01'#(lf)        AND encode(card._Fld681RRef, 'hex') IN (SELECT client_link FROM pz_visited)#(lf))#(lf)#(lf)SELECT #(lf)    pv.visit_date::date,#(lf)    pv.client_code,#(lf)    pv.visit_club AS club,#(lf)    pv.service_name,#(lf)#(tab)lc.contr#(lf)FROM pz_visited pv#(lf)LEFT JOIN last_contract lc #(lf)    ON lc.client_link = pv.client_link AND lc.rn = 1#(lf)WHERE #(lf)pv.visit_date >= '2025-10-01' #(lf)    AND (lc.contract_end > pv.class_start OR lc.contract_end IS NULL)"),
    #"Измененный тип" = Table.TransformColumns(Источник, {{"visit_date", each DateTime.From(Date.From(_)), type datetime}}),
    #"Строки с примененным фильтром" = Table.SelectRows(#"Измененный тип", each ([club] = "Пушкинский")),
    #"Другие удаленные столбцы" = Table.SelectColumns(#"Строки с примененным фильтром",{"client_code", "visit_date"}),
    #"Сгруппированные строки" = Table.Group(#"Другие удаленные столбцы", {"client_code", "visit_date"}, {{"Количество", each Table.RowCount(_), Int64.Type}})
in
    #"Сгруппированные строки"  Посещения ГП  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "#(lf)SELECT #(lf)    cast(main._Description as varchar(1000)) Клуб    #(lf)    ,_Document279._Fld3218 ДатаСобытия#(lf)    ,_InfoRg8675._Fld8677 Посетило#(lf)    ,cast(_Fld3229 as varchar(1000)) ПредставлениеДокумента    #(lf)FROM _Document279#(lf)left join _Reference132 as main on --основной клуб доступа#(lf)main._IDRRef = _Document279._Fld3224RRef#(lf)left join _Reference191 on#(lf)_Document279._Fld3227RRef= _Reference191._IDRRef#(lf)left join _InfoRg8675 on #(lf)_InfoRg8675._Fld8676RRef = _Document279._IDRRef#(lf)#(lf)where#(lf)_Fld3218 >= '01.10.2025'#(lf)and _Document279._Posted='1'#(lf)and _InfoRg8675._Fld8677 is not null#(lf)and cast(main._Description as varchar(1000)) = 'Пушкинский'"),
    #"Измененный тип" = Table.TransformColumns(Источник, {{"ДатаСобытия", each DateTime.From(Date.From(_)), type datetime}})
in
    #"Измененный тип"  Посещения платно ДПФУ  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "with clients (id, code, client_type) as#(lf)(#(lf)SELECT #(lf)    encode(_IDRRef,'hex') id#(lf)    ,cast(_Code as varchar(1000)) code#(lf)    ,encode(_Fld1532RRef,'hex') client_type#(lf)from _Reference141X1#(lf)),#(lf)#(lf)main_club (client,club,startdate,enddate) as#(lf)(#(lf)SELECT #(lf)    cast(_Reference141X1._Code as varchar(1000)) client#(lf)    ,(cast(_Reference132._Description as varchar(1000)))as club  #(lf)    ,_Fld671 startdate#(lf)    ,_Fld672 enddate#(lf)#(lf)FROM _Reference59#(lf)  left join _Reference141X1#(lf)  on _Reference141X1._IDRRef=_Reference59._Fld681RRef#(lf)  left join _Reference132 #(lf)  on _Reference132._IDRRef=_Reference59._Fld687RRef#(lf)  where cast(_Reference132._Description as varchar(1000)) is not null#(lf)  and encode(_Fld696RRef,'hex')='bf4b50662e88eb7b44046ebf4849976f' --Тип контракта = контракт#(lf)),#(lf)tab1 (period,club, client_code, client_type,paiment_type, number) as#(lf)(--РегистрНакопления.Посещения (Основная)#(lf)SELECT #(lf)  _Period period#(lf)  ,cast(_Reference132._Description as varchar(1000)) club            #(lf)  ,clients.code client_code   #(lf)  ,case#(lf)    when _Fld7583 = '1' --Гость = Да#(lf)    then 'Прочие'#(lf)    when clients.client_type = '8e3e8dea66a1d5454387ceb554c10615' -- ТипКлиента = Сотрудник#(lf)    then 'Сотрудник'#(lf)    else 'Клиент'#(lf)  end as client_type#(lf)  ,case#(lf)    when cast(_Reference59._Code as varchar(1000)) is not null#(lf)    then#(lf)      case #(lf)        when encode(_Reference59._Fld696RRef,'hex')='bf4b50662e88eb7b44046ebf4849976f' --Тип контракта = контракт#(lf)        then 'Купон'#(lf)        else 'Клип-Карта'#(lf)      end#(lf)    else 'Чек'#(lf)  end as paiment_type#(lf)  ,sum(_Fld7585) number#(lf)#(lf)FROM _AccumRg7575#(lf)  left join clients#(lf)  on encode(_Fld7576RRef,'hex') = clients.id#(lf)  left join _Reference132#(lf)  on _Fld7577RRef = _Reference132._IDRRef#(lf)  left join _Reference163 #(lf)  on _Fld7579RRef = _Reference163._IDRRef#(lf)  left join _Reference70 #(lf)  on _Reference163._Fld1733RRef = _Reference70._IDRRef#(lf)  left join _Reference59 #(lf)  on _Fld7578_RRRef = _Reference59._IDRRef#(lf)#(lf)where #(lf)  _AccumRg7575._Period>='01.11.2025' and _AccumRg7575._Period < CURRENT_DATE#(lf)  and encode(_Fld1795RRef,'hex') ='9f007d77d46892dc47058346701d3bb6' --ТипНоменклатуры = ""Услуга""#(lf)  and encode(_Reference70._Fld843RRef,'hex') <> '9e10e872e49a551b4968a66b95c28905' --Бизнес направление не равно ""Прочие членство""#(lf)  and encode(_Reference70._Fld843RRef,'hex') <> 'ac626c95655c992a471b27ca8f8812cd' --Бизнес направление не равно ""Членство""#(lf)  and cast(_Reference163._Description as varchar(1000))<>'посещение клуба' -- Услуга не равно ""Посещение клуба""#(lf)  and cast(_Reference70._Description as varchar(1000)) in ('Игровой зал','Восстановительный фитнес','Боевые искусства','Детский клуб','Водные программы','Групповые программы','Тренажёрный зал','Тренажерный зал')#(lf)#(lf)group by#(lf)  _Period#(lf)  ,cast(_Reference132._Description as varchar(1000))       #(lf)    ,cast(_Reference163._Fld1761 as varchar(1000))          #(lf)  ,clients.code    #(lf)  ,case#(lf)    when _Fld7583 = '1' --Гость = Да#(lf)    then 'Прочие'#(lf)    when clients.client_type = '8e3e8dea66a1d5454387ceb554c10615' -- ТипКлиента = Сотрудник#(lf)    then 'Сотрудник'#(lf)    else 'Клиент'#(lf)  end #(lf)  ,case#(lf)    when cast(_Reference59._Code as varchar(1000)) is not null#(lf)    then#(lf)      case #(lf)        when encode(_Reference59._Fld696RRef,'hex')='bf4b50662e88eb7b44046ebf4849976f' --Тип контракта = контракт#(lf)        then 'Купон'#(lf)        else 'Клип-Карта'#(lf)      end#(lf)    else 'Чек'#(lf)  end #(lf)),#(lf)tab2 (period,club, client_code, client_type,paiment_type, number) as#(lf)(#(lf)SELECT #(lf)  _Period period#(lf)  ,cast(_Reference132._Description as varchar(1000)) club        #(lf)  ,clients.code client_code   #(lf)  ,case#(lf)    when _Fld7656 = '1' --Гость = Да#(lf)    then 'Прочие'#(lf)    when clients.client_type = '8e3e8dea66a1d5454387ceb554c10615' -- ТипКлиента = Сотрудник#(lf)    then 'Сотрудник'#(lf)    else 'Клиент'#(lf)  end as client_type#(lf)  ,'Чек' as paiment_type#(lf)  ,sum(_Fld7657) number#(lf)FROM _AccumRg7646#(lf)  left join clients#(lf)  on encode(_Fld7648RRef,'hex') = clients.id#(lf)  left join _Reference132#(lf)  on _Fld7653RRef = _Reference132._IDRRef#(lf)  left join _Reference163 #(lf)  on _Fld7649RRef = _Reference163._IDRRef#(lf)  left join _Reference70 #(lf)  on _Reference163._Fld1733RRef = _Reference70._IDRRef#(lf)  left join _Reference59#(lf)  on _Fld7655RRef = _Reference59._IDRRef#(lf)  left join main_club #(lf)  on   clients.code = main_club.client#(lf)where #(lf)  _AccumRg7646._Period>='01.11.2025' and _AccumRg7646._Period<CURRENT_DATE#(lf)  and encode(_Fld1795RRef,'hex') <> '9f007d77d46892dc47058346701d3bb6' --ТипНоменклатуры не равно услуга#(lf)  AND encode(_Fld1795RRef,'hex') <> '89de5e634e304b1a44efac5ab7088373' -- Тип Номенклатуры не равно Абонемент#(lf)  and encode(_Fld1795RRef,'hex') <> 'baad3eba9d9fe9b441d2a1a897435c33' -- Тип номенклатуры не равно ПодарочныйСертификат#(lf)  and encode(_Reference70._Fld843RRef,'hex') <> '9e10e872e49a551b4968a66b95c28905' --Бизнес направление не равно ""Прочие членство""#(lf)  and encode(_Reference70._Fld843RRef,'hex') <> 'ac626c95655c992a471b27ca8f8812cd' --Бизнес направление не равно ""Членство""#(lf)  and cast(_Reference163._Description as varchar(1000))<>'посещение клуба' -- Услуга не равно ""Посещение клуба""#(lf)  and cast(_Reference70._Description as varchar(1000)) in ('Игровой зал','Восстановительный фитнес','Боевые искусства','Детский клуб','Водные программы','Групповые программы','Тренажёрный зал','Тренажерный зал')#(lf)#(lf)  group by#(lf)  _Period#(lf)  ,cast(_Reference132._Description as varchar(1000))       #(lf)    ,cast(_Reference163._Fld1761 as varchar(1000))        #(lf)    ,cast(_Reference70._Description as varchar(1000))          #(lf)  ,clients.code  #(lf)  ,case#(lf)    when _Fld7656 = '1' --Гость = Да#(lf)    then 'Прочие'#(lf)    when clients.client_type = '8e3e8dea66a1d5454387ceb554c10615' -- ТипКлиента = Сотрудник#(lf)    then 'Сотрудник'#(lf)    else 'Клиент'#(lf)  end #(lf)    ,""paiment_type""#(lf))#(lf)#(lf)--РегистрНакопления.Посещения (Основная)#(lf)SELECT #(lf)  tab1.period Период#(lf)  ,tab1.club Клуб         #(lf)  ,tab1.client_code КодКлиента#(lf)  ,tab1.number Количество  #(lf)  ,tab1.client_type ПризнакКлиента#(lf)  ,tab1.paiment_type ТипОплаты#(lf)  ,max (#(lf)    CASE#(lf)      when main_club.startdate is NULL#(lf)      then NULL#(lf)      when main_club.startdate <=period and main_club.enddate >=period#(lf)      then main_club.club#(lf)      else NULL#(lf)    end) as ОсновнойКлубДоступа#(lf)#(lf)FROM tab1#(lf)  left join main_club #(lf)  on   tab1.client_code = main_club.client#(lf)#(lf)where #(lf)--ОсновнойКлубДоступа = 'Пушкинский'#(lf)--and #(lf)tab1.paiment_type <> 'Купон'#(lf)and tab1.client_type <> 'Сотрудник'#(lf)#(lf)group by#(lf)  tab1.period #(lf)  ,tab1.club           #(lf)  ,tab1.client_code #(lf)  ,tab1.number  #(lf)  ,tab1.client_type #(lf)  ,tab1.paiment_type #(lf)#(lf)union all#(lf)#(lf)-- Продажи#(lf)SELECT #(lf)  tab2.period Период#(lf)  ,tab2.club Клуб          #(lf)  ,tab2.client_code КодКлиента#(lf)  ,tab2.number Количество#(lf)  ,tab2.client_type ПризнакКлиента#(lf)  ,tab2.paiment_type ТипОплаты#(lf)  ,max (#(lf)    CASE#(lf)      when main_club.startdate is NULL#(lf)      then NULL#(lf)      when main_club.startdate <=period and main_club.enddate >=period#(lf)      then main_club.club#(lf)      else NULL#(lf)    end) as ОсновнойКлубДоступа#(lf)#(lf)FROM tab2#(lf)  left join main_club #(lf)  on   tab2.client_code = main_club.client#(lf)#(lf)where #(lf)--ОсновнойКлубДоступа = 'Пушкинский'#(lf)--and #(lf)tab2.paiment_type <> 'Купон'#(lf)and tab2.client_type <> 'Сотрудник'#(lf)#(lf)group by#(lf)  tab2.period #(lf)  ,tab2.club             #(lf)  ,tab2.client_code #(lf)  ,tab2.number #(lf)  ,tab2.client_type #(lf)  ,tab2.paiment_type#(lf)"),
    #"Строки с примененным фильтром1" = Table.SelectRows(Источник, each ([ОсновнойКлубДоступа] = "Пушкинский")),
    #"Измененный тип" = Table.TransformColumns(#"Строки с примененным фильтром1", {{"Период", each DateTime.From(Date.From(_)), type datetime}}),
    #"Строки с примененным фильтром" = Table.SelectRows(#"Измененный тип", each ([ОсновнойКлубДоступа] = "Пушкинский")),
    #"Удаленные столбцы" = Table.RemoveColumns(#"Строки с примененным фильтром",{"Клуб", "ПризнакКлиента", "ТипОплаты", "ОсновнойКлубДоступа"})
in
    #"Удаленные столбцы"  Посещения ДРЦ  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "SELECT #(lf)    _AccumRg7575._Period::date as Период, #(lf)    cast(main._Description as varchar(1000)) as Клуб,#(lf)    cast(_Reference132._Description as varchar(1000)) as КлубПосещения,#(lf)    cast(_Reference141X1._Code as varchar(1000)) as КодКлиента,#(lf)    cast(_Reference59._Description as varchar(1000)) as Услуга#(lf)FROM _AccumRg7575#(lf)#(lf)left join _Document325#(lf)#(tab)on _RecorderRRef = _Document325._IDRRef#(lf)#(lf)left join _Reference141X1#(lf)#(tab)on _Document325._Fld4171RRef = _Reference141X1._IDRRef#(lf)#(lf)left join _Reference59#(lf)    on   _AccumRg7575._Fld7578_RRRef = _Reference59._IDRRef#(tab)#(lf)#(tab)#(lf)left join _Reference163#(lf)    on _Reference59._Fld685RRef =  _Reference163._IDRRef#(lf)#(tab)#(lf)left join _Reference132 as main --основной клуб доступа#(lf)    on _Reference59._Fld687RRef = main._IDRRef#(tab)#(lf)left join _Reference132 --по посещению#(lf)#(tab)on _Document325._Fld4167RRef =_Reference132._IDRRef#(lf)#(lf)where #(lf)    encode(_Document325._Fld4164RRef,'hex')='9a5a4c90d2b1aede4b91dcd1abe84c43' --ВидПосещенияНовый = посещение#(lf)    AND date_trunc('day',_AccumRg7575._Period::date) >= '01.10.2025'#(lf)        and date_trunc('day',_AccumRg7575._Period::date) < current_date#(lf)    AND encode(_Reference141X1._Fld1532RRef,'hex') = '9e8eaa7b2e77c19f4a1c22a8d9c3efa1' -- ТипКлиента = Клиент#(lf)   and cast(main._Description as varchar(1000)) = 'Детский развивающий центр'#(lf)and cast(_Reference132._Description as varchar(1000)) = 'Пушкинский'#(lf)#(lf)and lower(cast(_Reference163._Description as varchar(1000))) not like '%контракт сотрудника%'#(lf) and (lower(cast(_Reference163._Description as varchar(1000))) not LIKE '%продленка%' or #(lf)     lower(cast(_Reference163._Description as varchar(1000))) not LIKE '%продлёнка%')#(lf) and lower(cast(_Reference163._Description as varchar(1000))) not LIKE '%умняши%' "),
    #"Сгруппированные строки" = Table.Group(Источник, {"Период", "КодКлиента"}, {{"Количество", each Table.RowCount(_), Int64.Type}}),
    #"Сортированные строки" = Table.Sort(#"Сгруппированные строки",{{"Период", Order.Ascending}})
in
    #"Сортированные строки"  Посещения продленкаlet
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test", "SELECT #(lf)    _AccumRg7575._Period::date as Период, #(lf)   cast(main._Description as varchar(1000)) as Клуб,#(lf)   cast(_Reference132._Description as varchar(1000)) as КлубПосещения,#(lf)#(lf)    cast(_Reference141X1._Code as varchar(1000)) as КодКлиента,#(lf)    cast(_Reference59._Description as varchar(1000)) as Услуга#(lf)FROM _AccumRg7575#(lf)#(lf)left join _Document325#(lf)#(tab)on _RecorderRRef = _Document325._IDRRef#(lf)#(lf)left join _Reference141X1#(lf)#(tab)on _Document325._Fld4171RRef = _Reference141X1._IDRRef#(lf)#(lf)left join _Reference59#(lf)    on   _AccumRg7575._Fld7578_RRRef = _Reference59._IDRRef#(tab)#(lf)#(tab)#(lf)left join _Reference163#(lf)    on _Reference59._Fld685RRef =  _Reference163._IDRRef#(lf)#(tab)#(lf)left join _Reference132 as main --основной клуб доступа#(lf)    on _Reference59._Fld687RRef = main._IDRRef#(tab)#(lf)left join _Reference132 --по посещению#(lf)#(tab)on _Document325._Fld4167RRef =_Reference132._IDRRef#(lf)#(lf)where #(lf)    encode(_Document325._Fld4164RRef,'hex')='9a5a4c90d2b1aede4b91dcd1abe84c43' --ВидПосещенияНовый = посещение#(lf)    AND date_trunc('day',_AccumRg7575._Period::date) >= '01.10.2025'#(lf)        and date_trunc('day',_AccumRg7575._Period::date) < current_date#(lf)    AND encode(_Reference141X1._Fld1532RRef,'hex') = '9e8eaa7b2e77c19f4a1c22a8d9c3efa1' -- ТипКлиента = Клиент#(lf)  and cast(_Reference132._Description as varchar(1000)) = 'Пушкинский'#(lf)  and cast(main._Description as varchar(1000)) = 'Детский развивающий центр'#(lf)    #(lf) and (#(lf)    lower(cast(_Reference163._Description as varchar(1000))) LIKE '%продленка%' #(lf)    or lower(cast(_Reference163._Description as varchar(1000))) LIKE '%продлёнка%'#(lf))    --and lower(cast(_Reference163._Description as varchar(1000))) NOT LIKE '%гость кафе%'"),
    #"Сгруппированные строки" = Table.Group(Источник, {"Период", "КодКлиента"}, {{"Количество", each Table.RowCount(_), Int64.Type}}),
    #"Сортированные строки" = Table.Sort(#"Сгруппированные строки",{{"Период", Order.Ascending}})
in
    #"Сортированные строки"  Посещения умняши  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;", "SELECT #(lf)    _AccumRg7575._Period::date as Период, #(lf)    cast(main._Description as varchar(1000)) as Клуб,#(lf)    cast(_Reference132._Description as varchar(1000)) as КлубПосещения,#(lf)    cast(_Reference141X1._Code as varchar(1000)) as КодКлиента,#(lf)    cast(_Reference59._Description as varchar(1000)) as Услуга#(lf)FROM _AccumRg7575#(lf)#(lf)left join _Document325#(lf)#(tab)on _RecorderRRef = _Document325._IDRRef#(lf)#(lf)left join _Reference141X1#(lf)#(tab)on _Document325._Fld4171RRef = _Reference141X1._IDRRef#(lf)#(lf)left join _Reference59#(lf)    on   _AccumRg7575._Fld7578_RRRef = _Reference59._IDRRef#(tab)#(lf)#(tab)#(lf)left join _Reference163#(lf)    on _Reference59._Fld685RRef =  _Reference163._IDRRef#(lf)#(tab)#(lf)left join _Reference132 as main --основной клуб доступа#(lf)    on _Reference59._Fld687RRef = main._IDRRef#(tab)#(lf)left join _Reference132 --по посещению#(lf)#(tab)on _Document325._Fld4167RRef=_Reference132._IDRRef#(lf)#(lf)where #(lf)    encode(_Document325._Fld4164RRef,'hex')='9a5a4c90d2b1aede4b91dcd1abe84c43' --ВидПосещенияНовый = посещение#(lf)    AND date_trunc('day',_AccumRg7575._Period::date) >= '01.10.2025'#(lf)        and date_trunc('day',_AccumRg7575._Period::date) < current_date#(lf)    AND encode(_Reference141X1._Fld1532RRef,'hex') = '9e8eaa7b2e77c19f4a1c22a8d9c3efa1' -- ТипКлиента = Клиент#(lf)  and cast(_Reference132._Description as varchar(1000)) = 'Пушкинский'#(lf)  and cast(main._Description as varchar(1000)) = 'Детский развивающий центр'#(lf)#(lf) and cast(_Reference163._Description as varchar(1000)) ILIKE '%умняши%' #(lf)    --and lower(cast(_Reference163._Description as varchar(1000))) NOT LIKE '%гость кафе%'"),
    #"Сгруппированные строки" = Table.Group(Источник, {"Период", "КодКлиента"}, {{"Количество", each Table.RowCount(_), Int64.Type}}),
    #"Сортированные строки" = Table.Sort(#"Сгруппированные строки",{{"Период", Order.Ascending}})
in
    #"Сортированные строки"  Посещения ГВ  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "SELECT #(lf)    _AccumRg7575._Period::date as Период, #(lf)  --  cast(main._Description as varchar(1000)) as Клуб,#(lf)    cast(_Reference132._Description as varchar(1000)) as КлубПосещения,#(lf)    cast(_Reference141X1._Code as varchar(1000)) as КодКлиента,#(lf)    cast(_Reference163._Description as varchar(1000)) as Услуга#(lf)FROM _AccumRg7575#(lf)#(lf)left join _Document325#(lf)#(tab)on _RecorderRRef = _Document325._IDRRef#(lf)#(lf)left join _Reference141X1#(lf)#(tab)on _Document325._Fld4171RRef = _Reference141X1._IDRRef#(lf)#(lf)--left join _Reference59#(lf)--    on   encode(_AccumRg7575._Fld7578_RRRef,'hex') = encode(_Reference59._IDRRef,'hex')#(tab)#(lf)#(tab)#(lf)left join _Reference163#(lf)    on _AccumRg7575._Fld7579RRef =  _Reference163._IDRRef#(lf)#(tab)#(lf)--left join _Reference132 as main --основной клуб доступа#(lf) --   on encode(_Reference59._Fld687RRef,'hex') = encode(main._IDRRef,'hex')#(tab)#(lf)left join _Reference132 --по посещению#(lf)#(tab)on _Document325._Fld4167RRef =_Reference132._IDRRef#(lf)#(lf)where #(lf)encode(_Document325._Fld4164RRef,'hex')='9a5a4c90d2b1aede4b91dcd1abe84c43' --ВидПосещенияНовый = посещение#(lf)    #(lf)AND date_trunc('day',_AccumRg7575._Period::date) >= '01.10.2025'#(lf)    and date_trunc('day',_AccumRg7575._Period::date) < current_date#(lf)#(lf)AND encode(_Reference141X1._Fld1532RRef,'hex') = '9e8eaa7b2e77c19f4a1c22a8d9c3efa1' -- ТипКлиента = Клиент#(lf)   #(lf)  and cast(_Reference132._Description as varchar(1000)) = 'Пушкинский'#(lf) -- and cast(main._Description as varchar(1000)) = 'Пушкинский'#(lf) #(lf)--документ основание - ГВ#(lf)--and encode(_Reference163._Fld1795RRef,'hex') = '88bde25895157a1144e7e66430928318' #(lf)#(lf)and (cast(_Reference163._Description as varchar(1000)) ILIKE '%гостевой визит%' or #(lf)cast(_Reference163._Description as varchar(1000)) ILIKE '%гост%') #(lf)and lower(cast(_Reference163._Description as varchar(1000))) NOT LIKE '%гость кафе%'"),
    #"Сгруппированные строки" = Table.Group(Источник, {"Период", "КодКлиента"}, {{"Количество", each Table.RowCount(_), Int64.Type}})
in
    #"Сгруппированные строки"  Посещения ВИП  let
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "SELECT #(lf)    _AccumRg7575._Period::date as Период, #(lf)   cast(main._Description as varchar(1000)) as Клуб,#(lf)   cast(_Reference132._Description as varchar(1000)) as КлубПосещения,#(lf)    cast(_Reference141X1._Code as varchar(1000)) as КодКлиента,#(lf)    cast(_Reference59._Description as varchar(1000)) as Услуга#(lf)FROM _AccumRg7575#(lf)#(lf)left join _Document325#(lf)#(tab)on _RecorderRRef = _Document325._IDRRef#(lf)#(lf)left join _Reference141X1#(lf)#(tab)on _Document325._Fld4171RRef = _Reference141X1._IDRRef#(lf)#(lf)left join _Reference59#(lf)    on   _AccumRg7575._Fld7578_RRRef = _Reference59._IDRRef#(tab)#(lf)#(tab)#(lf)left join _Reference163#(lf)    on _Reference59._Fld685RRef =  _Reference163._IDRRef#(lf)#(tab)#(lf)left join _Reference132 as main --основной клуб доступа#(lf)    on _Reference59._Fld687RRef = main._IDRRef#(tab)#(lf)left join _Reference132 --по посещению#(lf)#(tab)on _Document325._Fld4167RRef =_Reference132._IDRRef#(lf)#(lf)where #(lf)    encode(_Document325._Fld4164RRef,'hex')='9a5a4c90d2b1aede4b91dcd1abe84c43' --ВидПосещенияНовый = посещение#(lf)    AND date_trunc('day',_AccumRg7575._Period::date) >= '01.10.2025'#(lf)        and date_trunc('day',_AccumRg7575._Period::date) < current_date#(lf)    AND encode(_Reference141X1._Fld1532RRef,'hex') = '9e8eaa7b2e77c19f4a1c22a8d9c3efa1' -- ТипКлиента = Клиент#(lf)  -- and cast(_Reference132._Description as varchar(1000)) = 'Пушкинский VIP'#(lf)  and cast(_Reference132._Description as varchar(1000)) = 'Пушкинский'#(lf)  and cast(main._Description as varchar(1000)) = 'Пушкинский VIP'#(lf)#(lf)and lower(cast(_Reference163._Description as varchar(1000))) not like '%контракт сотрудника%'"),
    #"Сгруппированные строки" = Table.Group(Источник, {"Период", "КодКлиента"}, {{"Количество", each Table.RowCount(_), Int64.Type}}),
    #"Сортированные строки" = Table.Sort(#"Сгруппированные строки",{{"Период", Order.Ascending}})
in
    #"Сортированные строки"  Посещения проверка ДПФУlet
    Источник = Odbc.Query("Driver={PostgreSQL Unicode};Server=virt207.worldclass.nnov.ru; Database=gymdb_test;Timeout=300;Fetch=10000;UseDeclareFetch=1;", "WITH clients AS (#(lf)    SELECT#(lf)        _IDRRef AS id,#(lf)        _Code::TEXT AS code,#(lf)        _Fld1532RRef AS client_type#(lf)    FROM _Reference141X1#(lf)),#(lf)main_club AS (#(lf)    SELECT#(lf)        r141._Code::TEXT AS client,#(lf)        r132._Description::TEXT AS club,#(lf)        r59._Fld671 AS startdate,#(lf)        r59._Fld672 AS enddate#(lf)    FROM _Reference59 r59#(lf)    LEFT JOIN _Reference141X1 r141 ON r59._Fld681RRef = r141._IDRRef#(lf)    LEFT JOIN _Reference132 r132 ON r59._Fld687RRef = r132._IDRRef#(lf)    WHERE#(lf)        r132._Description IS NOT NULL#(lf)        AND r59._Fld696RRef = '\xbf4b50662e88eb7b44046ebf4849976f'::bytea  -- Тип контракта = контракт#(lf)),#(lf)training_dates AS (#(lf)    SELECT #(lf)_IDRRef AS doc_ref, #(lf)_Fld3218::DATE AS training_date #(lf)FROM _Document279 #(lf)WHERE _Posted = true#(lf)    UNION ALL#(lf)    SELECT #(lf)_IDRRef AS doc_ref, #(lf)_Fld4306::DATE AS training_date #(lf)FROM _Document329 #(lf)WHERE _Posted = true#(lf)),#(lf)tab1 AS (#(lf)    SELECT#(lf)        td.training_date AS period,#(lf)        r132._Description::TEXT AS club,#(lf)        c.code AS client_code,#(lf)        CASE#(lf)            WHEN a._Fld7583 = '1' THEN 'Прочие'#(lf)            WHEN c.client_type = '\x8e3e8dea66a1d5454387ceb554c10615'::bytea THEN 'Сотрудник'#(lf)            ELSE 'Клиент'#(lf)        END AS client_type,#(lf)        CASE#(lf)            WHEN r59._Code IS NOT NULL THEN#(lf)                CASE#(lf)                    WHEN r59._Fld696RRef = '\xbf4b50662e88eb7b44046ebf4849976f'::bytea #(lf)THEN 'Купон'#(lf)                    ELSE 'Клип-Карта'#(lf)                END#(lf)            ELSE 'Чек'#(lf)        END AS paiment_type,#(lf)        SUM(a._Fld7585) AS number#(lf)    FROM _AccumRg7575 a#(lf)    INNER JOIN training_dates td ON a._Fld7581_RRRef = td.doc_ref#(lf)    LEFT JOIN clients c ON a._Fld7576RRef = c.id#(lf)    LEFT JOIN _Reference132 r132 ON a._Fld7577RRef = r132._IDRRef#(lf)    LEFT JOIN _Reference163 r163 ON a._Fld7579RRef = r163._IDRRef#(lf)    LEFT JOIN _Reference70 r70 ON r163._Fld1733RRef = r70._IDRRef#(lf)    LEFT JOIN _Reference59 r59 ON a._Fld7578_RRRef = r59._IDRRef#(lf)    WHERE#(lf)        td.training_date >= '2025-10-01'::DATE#(lf)        AND td.training_date < CURRENT_DATE#(lf)        AND r163._Fld1795RRef = '\x9f007d77d46892dc47058346701d3bb6'::bytea  -- Услуга#(lf)        AND COALESCE(r70._Fld843RRef, '\x00'::bytea) NOT IN (#(lf)            '\x9e10e872e49a551b4968a66b95c28905'::bytea,  -- Прочие членство#(lf)            '\xac626c95655c992a471b27ca8f8812cd'::bytea   -- Членство#(lf)        )#(lf)        AND COALESCE(r163._Description, '') <> 'посещение клуба'#(lf)        AND r70._Description::TEXT IN (#(lf)            'Игровой зал','Восстановительный фитнес','Боевые искусства',#(lf)            'Детский клуб','Водные программы','Групповые программы',#(lf)            'Тренажёрный зал','Тренажерный зал'#(lf)        )#(lf)    GROUP BY#(lf)        td.training_date,#(lf)        r132._Description,#(lf)        c.code,#(lf)        CASE#(lf)            WHEN a._Fld7583 = '1' THEN 'Прочие'#(lf)            WHEN c.client_type = '\x8e3e8dea66a1d5454387ceb554c10615'::bytea #(lf)THEN 'Сотрудник'#(lf)            ELSE 'Клиент'#(lf)        END,#(lf)        CASE#(lf)            WHEN r59._Code IS NOT NULL THEN#(lf)                CASE#(lf)                    WHEN r59._Fld696RRef = '\xbf4b50662e88eb7b44046ebf4849976f'::bytea #(lf)THEN 'Купон'#(lf)                    ELSE 'Клип-Карта'#(lf)                END#(lf)            ELSE 'Чек'#(lf)        END#(lf)),#(lf)final_data AS (#(lf)    SELECT#(lf)        t.period,#(lf)        t.club,#(lf)        t.client_code,#(lf)        t.number,#(lf)        t.client_type,#(lf)        t.paiment_type,#(lf)        MAX(#(lf)            CASE#(lf)                WHEN mc.startdate IS NULL THEN NULL#(lf)                WHEN mc.startdate <= t.period AND mc.enddate >= t.period THEN mc.club#(lf)                ELSE NULL#(lf)            END#(lf)        ) AS ОсновнойКлубДоступа#(lf)    FROM tab1 t#(lf)    LEFT JOIN main_club mc ON t.client_code = mc.client#(lf)    GROUP BY#(lf)        t.period,#(lf)        t.club,#(lf)        t.client_code,#(lf)        t.number,#(lf)        t.client_type,#(lf)        t.paiment_type#(lf))#(lf)SELECT#(lf)    period AS Период,#(lf)    club AS Клуб,#(lf)    client_code AS КодКлиента,#(lf)    number AS Количество,#(lf)    client_type AS ПризнакКлиента,#(lf)    paiment_type AS ТипОплаты,#(lf)    ОсновнойКлубДоступа#(lf)FROM final_data#(lf)WHERE#(lf)    ОсновнойКлубДоступа = 'Пушкинский'#(lf)    AND paiment_type <> 'Купон'#(lf)    AND client_type <> 'Сотрудник'#(lf)ORDER BY period DESC;"),
    #"Строки с примененным фильтром1" = Table.SelectRows(Источник, each ([ОсновнойКлубДоступа] = "Пушкинский") and ([Клуб] = "Пушкинский")),
    #"Сгруппированные строки" = Table.Group(#"Строки с примененным фильтром1", {"Период", "КодКлиента"}, {{"Количество", each Table.RowCount(_), Int64.Type}})
in
    #"Сгруппированные строки"
